name: Build Nginx for Windows ARM64 with LLVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为构建环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install LLVM and Clang for cross-compilation
      run: |
        sudo apt update
        sudo apt install -y clang llvm lld build-essential

    - name: Install dependencies for Nginx
      run: |
        sudo apt update
        sudo apt install -y libpcre3 libpcre3-dev zlib1g zlib1g-dev libssl-dev

    - name: Download Nginx source
      run: |
        wget https://nginx.org/download/nginx-1.23.0.tar.gz
        tar -xzvf nginx-1.23.0.tar.gz

    - name: Configure Nginx for cross-compilation using LLVM
      run: |
        cd nginx-1.23.0
        # 设置编译器及目标参数
        export CC="clang --target=aarch64-w64-mingw32"
        export CXX="clang++ --target=aarch64-w64-mingw32"
        # 如果你有交叉构建支持，可以尝试使用 --crossbuild=ARM64，否则移除此参数
        ./configure \
          --crossbuild=ARM64 \
          --prefix=/tmp/nginx \
          --with-pcre \
          --with-zlib \
          --with-openssl

    - name: Build Nginx for ARM64 Windows using LLVM
      run: |
        cd nginx-1.23.0
        make
        make install DESTDIR=/tmp/nginx-arm64

    - name: Create Windows ARM64 executable package
      run: |
        cd /tmp/nginx-arm64
        zip -r nginx-arm64.zip .

    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: nginx-arm64
        path: /tmp/nginx-arm64/nginx-arm64.zip
